services:
  wordpress:
    build: ./wordpress
    ports:
      - 8080:80
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER:-exampleuser}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD:-examplepass}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME:-exampledb}
    volumes:
      - wordpress:/var/www/wordpress

  db:
    build: ./mysql
    environment:
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME:-exampledb}
      MYSQL_USER: ${WORDPRESS_DB_USER:-exampleuser}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD:-examplepass}
      MYSQL_RANDOM_ROOT_PASSWORD: ${SQL_ROOT_PASSWORD:-'admin'}
    volumes:
      - mysql:/var/lib/mysql
  
volumes:
  mysql:
  wordpress: