name: Azure Static Web Apps CI/CD

on:
  pull_request:
    types: [submitted]
    branches:
      - release/v*

jobs:
  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
          lfs: false
      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_GRASS_028E00E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/Lab2/copy-react-azure-static-web-app/todo-app" # App source code path
          api_location: "/Lab2/copy-react-azure-static-web-app/api/" # Api source code path - optional
          #output_location: "/Lab2/copy-react-azure-static-web-app/todo-app/build/static" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
