name: Azure Static Web Apps CI/CD

on:
  push:
    branches:
      - main
    paths:
      - Lab2/copy-react-azure-static-web-app/**
      - .github/workflows/lab2-pipeline.yml
  pull_request:
    types: [opened, synchronize, reopened, closed]
    branches:
      - main
    paths:
      - Lab2/copy-react-azure-static-web-app/**
      - .github/workflows/lab2-pipeline.yml

jobs:
  build_and_deploy_job:
    if: github.event_name == 'push' || (github.event_name == 'pull_request' && github.event.action != 'closed')
    runs-on: ubuntu-latest
    name: Build and Deploy Job

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: false
          lfs: false

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18.x'

      - name: Install Dependencies 
        run: cd Lab2/copy-react-azure-static-web-app/api && npm ci

      - name: Run Tests
        run: cd Lab2/copy-react-azure-static-web-app/api && npm test

      - name: Build And Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_GRASS_028E00E03 }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/Lab2/copy-react-azure-static-web-app/todo-app" # App source code path
          api_location: "/Lab2/copy-react-azure-static-web-app/api/" # Api source code path - optional
          output_location: "/Lab2/copy-react-azure-static-web-app/todo-app/dist" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
      
      

  close_pull_request_job:
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    name: Close Pull Request Job
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN_BLACK_GRASS_028E00E03 }}
          action: "close"
